### ISSUE TITLE
Change SQS name 

### ISSUE THREAD

**Issue by Puki4556** [platzio/terraform-aws-platzio#2]
Change the SQS to use ${var.name_prefix} instead of ${var.k8s_namespace}

**Comment by popen2** [comment]
Already fixed in 30f20a99993b4b8ef739eb6c5759f4e43c1d9e0e

**Comment by popen2** [comment]
Also credited in the release notes 🤩 https://platz.io/blog/2022/06/22/v0.4.2

**Comment by popen2** [comment]
Thank you again for reporting this issue!
